### ISSUE TITLE
about <query camera index> and <camera pose transformation>

### ISSUE THREAD

**Issue by xytjc** [YuanSun-XJTU/iComMa#12]
hello,i use the trained 3D gaussian module as input,but i dont know how to set the query camera index and camera pose transformation.This is my output:`(icomma) chengkang@chengkang-Z790-D:~/project/iComMa$ python run.py -m gaussian_module/garden --obs_img_index 0000 --delta "[30, 10, 5, 0.1, 0.2, 0.3]"
Looking for config file in gaussian_module/garden/cfg_args
Config file found: gaussian_module/garden/cfg_args
Loading trained model at iteration 30000 [17/05 16:44:24]
Reading camera 24/24 [17/05 16:44:24]
Loading Training Cameras [17/05 16:44:24]
Loading Test Cameras [17/05 16:44:26]
Traceback (most recent call last):
  File "/home/chengkang/project/iComMa/run.py", line 134, in <module>
    obs_view=scene.getTestCameras()[args.obs_img_index]
IndexError: list index out of range
`
Your work is great!

**Comment by xytjc** [comment]
thaks to yuan sun,my problem has been solved,we should run :`python run.py -m gaussian_module/garden --obs_img_index 0 --delta "[30, 10, 5, 0.1, 0.2, 0.3]" --eval`

**Comment by sunilmtma** [comment]
I am still getting the same type of error, what is gaussian_module/garden??


PS C:\Users\schoudhary\CESI\DEV\iComMa> python run.py -m "C:/Users/schoudhary/CESI/DEV/iComMa/850f750c-2" --obs_img_index 00092  --delta "15 10 5 0.1 0.2 0.3"
>> 
Looking for config file in C:/Users/schoudhary/CESI/DEV/iComMa/850f750c-2\cfg_args
Config file found: C:/Users/schoudhary/CESI/DEV/iComMa/850f750c-2\cfg_args
C:\Users\schoudhary\CESI\DEV\iComMa\utils\icomma_helper.py:13: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  LoFTR_model.load_state_dict(torch.load(ckpt_path)['state_dict'])
Loading trained model at iteration 30000 [23/10 16:14:17]
Reading camera 301/301 [23/10 16:14:17]
Loading Training Cameras [23/10 16:14:17]
Loading Test Cameras [23/10 16:14:20]
Traceback (most recent call last):
  File "C:\Users\schoudhary\CESI\DEV\iComMa\run.py", line 134, in <module>
    obs_view=scene.getTestCameras()[args.obs_img_index]
IndexError: list index out of range
